//APPLICATION CREATES A SEARCH TOOL THAT RETURNS: A BOOK RESULT BASED ON SEARCH WHICH SHOWS:
//BOOK TITLE, BOOK COVER, BOOK AUTHOR, BOOK PUBLISHED DAT

//FUNCTIONALITY: SORT RESULTS BY ALPHABETICALLY BY TITLE, SORT BY MOST RECENTLY PUBLISHED

//MANDATORY: RESPONSIVE UI, INCLUDE TESTS, WCAG/AA COMPLIANT, LIGHTHOUSE AUDIT, HOST ON GITHUB

import React from "react";
import BookCard from "./components/BookCard";

import "./styles.css";

const App = () => {

    return (
        <BookCard/>
    )
}

export default App;